# Generated by Django 4.2.5 on 2023-11-18 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abogado',
            fields=[
                ('basetrabajador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basetrabajador')),
                ('direccion', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Abogado',
                'verbose_name_plural': 'Abogados',
            },
            bases=('base.basetrabajador',),
        ),
        migrations.CreateModel(
            name='AsistenteControl',
            fields=[
                ('basetrabajador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basetrabajador')),
                ('grado_academico', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Asistente de Control',
                'verbose_name_plural': 'Asistentes de Control',
            },
            bases=('base.basetrabajador',),
        ),
        migrations.CreateModel(
            name='Comercial',
            fields=[
                ('basetrabajador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basetrabajador')),
                ('cantidad_contratos', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Comercial',
                'verbose_name_plural': 'Comerciales',
            },
            bases=('base.basetrabajador',),
        ),
        migrations.CreateModel(
            name='DepartamentoLegal',
            fields=[
                ('basedepartamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basedepartamento')),
                ('ano', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Departamento Legal',
                'verbose_name_plural': 'Departamentos Legales',
            },
            bases=('base.basedepartamento',),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('basetrabajador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basetrabajador')),
                ('grado_adademico', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directores',
            },
            bases=('base.basetrabajador',),
        ),
        migrations.CreateModel(
            name='Suministrador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('nombre_calle', models.CharField(max_length=50)),
                ('numero_calle', models.IntegerField()),
                ('municipio', models.CharField(max_length=60)),
                ('provincia', models.CharField(max_length=60)),
                ('clasificacion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Suministrador',
                'verbose_name_plural': 'Suministradores',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('departamentolegal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.departamentolegal')),
                ('clasificacion', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisiones',
            },
            bases=('app.departamentolegal',),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now=True)),
                ('id_comercial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.comercial')),
                ('id_suministrador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.suministrador')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_produccion', models.DateField()),
                ('id_suministador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.suministrador')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=50)),
                ('id_director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.director')),
            ],
            options={
                'verbose_name': 'Evaluacion',
                'verbose_name_plural': 'Evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='DepartamentoComercial',
            fields=[
                ('basedepartamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basedepartamento')),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('fecha_comunicacion', models.DateTimeField(default='')),
                ('id_DepartamentoLegal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departamentolegal')),
            ],
            options={
                'verbose_name': 'Departamento Comercial',
                'verbose_name_plural': 'Departamentos Comerciales',
            },
            bases=('base.basedepartamento',),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('id_departamentolegal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departamentolegal')),
                ('id_trabajador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.basetrabajador')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
